/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manual;

import Menu.Menu;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aazur
 */
public class Manual extends javax.swing.JFrame {

    FondoPanel panel = new FondoPanel();

    /**
     * Creates new form Manul
     */
    public Manual() {
        this.setContentPane(panel);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manual = new javax.swing.JTabbedPane();
        infogen = new javax.swing.JPanel();
        pag1 = new javax.swing.JScrollPane();
        tex1 = new javax.swing.JTextArea();
        blackjack = new javax.swing.JPanel();
        pag2 = new javax.swing.JScrollPane();
        tex2 = new javax.swing.JTextArea();
        piedrapt = new javax.swing.JPanel();
        pag3 = new javax.swing.JScrollPane();
        tex3 = new javax.swing.JTextArea();
        dados = new javax.swing.JPanel();
        pag4 = new javax.swing.JScrollPane();
        tex4 = new javax.swing.JTextArea();
        cartasalta = new javax.swing.JPanel();
        pag5 = new javax.swing.JScrollPane();
        tex5 = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("bdf");
        setUndecorated(true);
        setResizable(false);

        manual.setToolTipText("");
        manual.setAutoscrolls(true);
        manual.setFocusable(false);

        tex1.setColumns(20);
        tex1.setRows(5);
        tex1.setText("Información General sobre el Arcade 🎮🃏🎲\n\nBienvenido a The Lucky Arcade, un lugar \ndonde puedes disfrutar de distintos juegos de azar y\nestrategia.\nAquí puedes probar tu suerte y habilidades en varios\njuegos clásicos, apostando fichas virtuales en cada \npartida.\n\n📌 Funcionamiento del Sistema de Apuestas\nAl iniciar, recibirás una cantidad inicial de fichas.\nAntes de cada juego, puedes elegir cuántas fichas \napostar.\nSi ganas, duplicas tu apuesta.\nSi pierdes, las fichas apostadas se descontarán de \ntu saldo.\nSi empatas, ni pierdes ni ganas fichas.\n\n\n📌 Recordatorio: Si quieres no apostar puedes jugar sin \nhacerlo y no influencierá en su jugabilidad.");
        tex1.setFocusable(false);
        tex1.setRequestFocusEnabled(false);
        pag1.setViewportView(tex1);

        javax.swing.GroupLayout infogenLayout = new javax.swing.GroupLayout(infogen);
        infogen.setLayout(infogenLayout);
        infogenLayout.setHorizontalGroup(
            infogenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        infogenLayout.setVerticalGroup(
            infogenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        manual.addTab("General", infogen);

        tex2.setColumns(20);
        tex2.setRows(5);
        tex2.setText("🃏 Blackjack\nObjetivo: \n - Arcercarte lo más posible a 21 puntos sin pasarte.\n\nReglas:\n1. El jugador y el dealer reciben dos cartas al inicio.\n2. Las cartas numéricas valen su número, las figuras \n    (J, Q, K) Valen 10, y el As vale 1 u 11 según convenga.\n3. El jugador puede pedir cartas (Hit) o plantarse (Stand).\n4. Si la suma de las cartas del jugador supera 21, pierde \n    automáticamente.\n5. Cuando el jugador se planta, el dealer juega su turno.\n-  Gana quien tenga la suma más cercana a 21 sin pasarse.");
        tex2.setFocusable(false);
        pag2.setViewportView(tex2);

        javax.swing.GroupLayout blackjackLayout = new javax.swing.GroupLayout(blackjack);
        blackjack.setLayout(blackjackLayout);
        blackjackLayout.setHorizontalGroup(
            blackjackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        blackjackLayout.setVerticalGroup(
            blackjackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        manual.addTab("BJ", blackjack);
        blackjack.getAccessibleContext().setAccessibleName("BJ");

        tex3.setColumns(20);
        tex3.setRows(5);
        tex3.setText("✊✋✌️ Piedra, Papel o Tijera\nObjetivo: \n - Elegir una opción que venza la elección \ndel oponente.\n\nReglas:\n1. El jugador elige entre piedra 🪨, papel 📄 o tijera ✂️.\n2. La máquina también elige una opción al azar.\n3. Comparación de elecciones:\n    -Piedra gana contra Tijera.\n    -Tijera gana contra Papel.\n    -Papel gana contra Piedra.\n-  Si ambos eligen lo mismo, es un empate.\n");
        tex3.setFocusable(false);
        pag3.setViewportView(tex3);

        javax.swing.GroupLayout piedraptLayout = new javax.swing.GroupLayout(piedrapt);
        piedrapt.setLayout(piedraptLayout);
        piedraptLayout.setHorizontalGroup(
            piedraptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag3, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        piedraptLayout.setVerticalGroup(
            piedraptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        manual.addTab("PPT", piedrapt);

        tex4.setColumns(20);
        tex4.setRows(5);
        tex4.setText("🎲 Dados\nObjetivo:\n - Alcanzar 21.\n\nReglas:\n1. El jugador y la máquina lanzan dados y se apunta el \n   resultado y se va sumando con cada resultado.\n2. El primero en llegar a 21 puntos gana.\n-  Si ambos llegan o superan 21 a la vez, el que tenga más \npuntos gana.");
        tex4.setFocusable(false);
        pag4.setViewportView(tex4);

        javax.swing.GroupLayout dadosLayout = new javax.swing.GroupLayout(dados);
        dados.setLayout(dadosLayout);
        dadosLayout.setHorizontalGroup(
            dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag4, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        dadosLayout.setVerticalGroup(
            dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag4, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        manual.addTab("Dados", dados);

        tex5.setColumns(20);
        tex5.setRows(5);
        tex5.setText("🃏 Carta Alta\nObjetivo: Apostar si tu carta será mayor o menor que\n la del oponente.\n\nReglas:\n1. Se reparten una carta al jugador y otra a la máquina\n2. El jugador apuesta si su carta será mayor o menor \n   que la del rival.\n-  Si el jugador acierta, gana.\n-  Si el jugador no acierta, pierde.\n-  Si ambos tienen el mismo número, es un empate.");
        tex5.setFocusable(false);
        pag5.setViewportView(tex5);

        javax.swing.GroupLayout cartasaltaLayout = new javax.swing.GroupLayout(cartasalta);
        cartasalta.setLayout(cartasaltaLayout);
        cartasaltaLayout.setHorizontalGroup(
            cartasaltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        cartasaltaLayout.setVerticalGroup(
            cartasaltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pag5, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        manual.addTab("CA", cartasalta);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 255, 255));
        titulo.setText("Manual de uso");

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Manual/closechiquito.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manual, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(73, 73, 73)
                        .addComponent(cerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addComponent(cerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manual, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        manual.getAccessibleContext().setAccessibleName("BJ");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
            this.dispose();       
    }//GEN-LAST:event_cerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manual().setVisible(true);
            }
        });
    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Manual/fondomanual.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blackjack;
    private javax.swing.JPanel cartasalta;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPanel dados;
    private javax.swing.JPanel infogen;
    private javax.swing.JTabbedPane manual;
    private javax.swing.JScrollPane pag1;
    private javax.swing.JScrollPane pag2;
    private javax.swing.JScrollPane pag3;
    private javax.swing.JScrollPane pag4;
    private javax.swing.JScrollPane pag5;
    private javax.swing.JPanel piedrapt;
    private javax.swing.JTextArea tex1;
    private javax.swing.JTextArea tex2;
    private javax.swing.JTextArea tex3;
    private javax.swing.JTextArea tex4;
    private javax.swing.JTextArea tex5;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
