/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import CA.CA;
import Dados.Dados;
import Manual.Manual;
import blackjack.BlackJack;
import PPT.ppt;

import java.awt.Graphics;
import java.awt.Image;
import static java.awt.SystemColor.menu;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aazur
 */
public class Menu extends javax.swing.JFrame {

    private static UsuarioDAO usuarioDAO = new UsuarioDAO();
    private static int dinerousuario = 0;
    FondoPanel panel = new FondoPanel();
    private static String player;

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setContentPane(panel);
        initComponents();

    }

    public Menu(String user, int diner) {
        dinerousuario = diner;
        player = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        todo = new FondoPanel();
        black = new javax.swing.JLabel();
        ppt = new javax.swing.JLabel();
        dad = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        manual = new javax.swing.JLabel();
        cartal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/BJicono.png"))); // NOI18N
        black.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackMouseClicked(evt);
            }
        });

        ppt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/iconopiedra.png"))); // NOI18N
        ppt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pptMouseClicked(evt);
            }
        });

        dad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/logodado.png"))); // NOI18N
        dad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dadMouseClicked(evt);
            }
        });

        cerrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cerrar.setForeground(new java.awt.Color(204, 0, 153));
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/close.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        dinero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/mony2.png"))); // NOI18N
        dinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dineroMouseClicked(evt);
            }
        });

        manual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/interrogacion.png"))); // NOI18N
        manual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manualMouseClicked(evt);
            }
        });

        cartal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/cartas-de-poker.png"))); // NOI18N
        cartal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout todoLayout = new javax.swing.GroupLayout(todo);
        todo.setLayout(todoLayout);
        todoLayout.setHorizontalGroup(
            todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todoLayout.createSequentialGroup()
                .addGroup(todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todoLayout.createSequentialGroup()
                        .addGroup(todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(todoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(manual))
                            .addGroup(todoLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(black, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(dad)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ppt)
                        .addGap(92, 92, 92)))
                .addGroup(todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todoLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoLayout.createSequentialGroup()
                        .addComponent(cartal)
                        .addGap(46, 46, 46))))
        );
        todoLayout.setVerticalGroup(
            todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manual))
                .addGap(189, 189, 189)
                .addComponent(cartal)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(black, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))
                    .addGroup(todoLayout.createSequentialGroup()
                        .addComponent(dad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ppt)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(todo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(todo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void blackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackMouseClicked
        // TODO add your handling code here:
        BlackJack black = new BlackJack(player, dinerousuario);

        black.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_blackMouseClicked

    private void pptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pptMouseClicked
        // TODO add your handling code here:
        ppt piedra = new ppt(player, dinerousuario);

        piedra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pptMouseClicked

    private void dadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadMouseClicked
        // TODO add your handling code here:
        Dados dado = new Dados(player, dinerousuario);

        dado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dadMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO?", "SALIR", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_cerrarMouseClicked

    private void dineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dineroMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Tu saldo es de $" + dinerousuario);
    }//GEN-LAST:event_dineroMouseClicked

    private void manualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manualMouseClicked
        // TODO add your handling code here:
        Manual man = new Manual();

        man.setVisible(true);
    }//GEN-LAST:event_manualMouseClicked

    private void cartalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartalMouseClicked
        // TODO add your handling code here:
        CA car = new CA(player,dinerousuario);

        car.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cartalMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu(); // Crear la instancia del menú
                menu.setVisible(true); 

            }
        });

    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Menu/fondomenu.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel black;
    private javax.swing.JLabel cartal;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel dad;
    private javax.swing.JLabel dinero;
    private javax.swing.JLabel manual;
    private javax.swing.JLabel ppt;
    private javax.swing.JPanel todo;
    // End of variables declaration//GEN-END:variables
}
