/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CA;

import Menu.Menu;
import Menu.UsuarioDAO;
import Pantalla.Pantalla;
import blackjack.Baraja;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aazur
 */

public class CA extends javax.swing.JFrame {
    private Baraja baraja;
    
    FondoPanel panel = new FondoPanel();

    enum Apostar {
        cinco,
        diez,
        veinticinco,
        cincuenta,
        setentaycinco,
        cien,
        cero

    }
    private static int comprobaciondinero = 0;
    Apostar apostador = Apostar.cero;
    private static int apuestaenvivo = 0;
    ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Dados/fichicas.png"));
    ImageIcon imagen = new ImageIcon(getClass().getResource("/blackjack/DIfferent-BikeBack.png"));
    private static UsuarioDAO userdao = new UsuarioDAO();
    private static String usuar;
    private static int dinerouser = 0;
    /**
     * Creates new form CA
     */
    public CA() {
        this.setContentPane(panel);
        baraja = new Baraja();
        initComponents();
    }

    public CA(String us, int dinero) {
        dinerouser = dinero;
        comprobaciondinero=dinero;
        usuar = us;
        this.setContentPane(panel);
         baraja = new Baraja();
        initComponents();
        jug.setText(us);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        retroceder = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        diez = new javax.swing.JLabel();
        veinticinco = new javax.swing.JLabel();
        setentaycinco = new javax.swing.JLabel();
        cien = new javax.swing.JLabel();
        cincuenta = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        apuest = new javax.swing.JLabel();
        cartaJ = new javax.swing.JLabel();
        cartaM = new javax.swing.JLabel();
        jug = new javax.swing.JLabel();
        sis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("CARTA ALTA");

        retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/return.png"))); // NOI18N
        retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retrocederMouseClicked(evt);
            }
        });

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/close.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        money.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/mony2.png"))); // NOI18N
        money.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyMouseClicked(evt);
            }
        });

        diez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza10.png"))); // NOI18N
        diez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diezMouseClicked(evt);
            }
        });

        veinticinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza25.png"))); // NOI18N
        veinticinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veinticincoMouseClicked(evt);
            }
        });

        setentaycinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/moneda75 (2).png"))); // NOI18N
        setentaycinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setentaycincoMouseClicked(evt);
            }
        });

        cien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza100.png"))); // NOI18N
        cien.setToolTipText("");
        cien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cienMouseClicked(evt);
            }
        });

        cincuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza50.png"))); // NOI18N
        cincuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincuentaMouseClicked(evt);
            }
        });

        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza5.png"))); // NOI18N
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });

        apuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apuestMouseClicked(evt);
            }
        });

        cartaJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/Different-BikeBack.png"))); // NOI18N
        cartaJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaJMouseClicked(evt);
            }
        });

        cartaM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/Different-BikeBack.png"))); // NOI18N

        jug.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jug.setForeground(new java.awt.Color(255, 0, 255));
        jug.setText("Jugador");

        sis.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sis.setForeground(new java.awt.Color(255, 0, 255));
        sis.setText("Rival");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(retroceder)
                        .addGap(948, 948, 948)
                        .addComponent(money)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(cinco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diez)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veinticinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setentaycinco))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cien)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jug, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sis)
                        .addGap(218, 218, 218))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartaJ, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apuest, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(cartaM, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(cerrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(retroceder)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jug)
                                    .addComponent(sis))
                                .addGap(59, 59, 59)
                                .addComponent(cartaJ, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(cartaM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(money)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)
                        .addComponent(apuest, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cinco)
                    .addComponent(diez)
                    .addComponent(veinticinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setentaycinco)
                    .addComponent(cincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cien))
                .addGap(62, 62, 62))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void retrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrocederMouseClicked
        // TODO add your handling code here:

        this.setVisible(false); // Oculta la ventana actual
        new Menu().setVisible(true); // Crea y muestra el menú principal con el dinero actual
        this.dispose(); // Libera los recursos de la ventana actual

    }//GEN-LAST:event_retrocederMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO?", "SALIR", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_cerrarMouseClicked

    private void moneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Tu saldo es de $" + dinerouser);
    }//GEN-LAST:event_moneyMouseClicked

    private void diezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diezMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.diez;
        apostando();
    }//GEN-LAST:event_diezMouseClicked

    private void veinticincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veinticincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.veinticinco;
        apostando();
    }//GEN-LAST:event_veinticincoMouseClicked

    private void setentaycincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setentaycincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.setentaycinco;
        apostando();
    }//GEN-LAST:event_setentaycincoMouseClicked

    private void cienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cienMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cien;
        apostando();
    }//GEN-LAST:event_cienMouseClicked

    private void cincuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincuentaMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cincuenta;
        apostando();
    }//GEN-LAST:event_cincuentaMouseClicked

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cinco;
        apostando();
    }//GEN-LAST:event_cincoMouseClicked

    private void apuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apuestMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Estas apostando " + apuestaenvivo);
    }//GEN-LAST:event_apuestMouseClicked

    private void cartaJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaJMouseClicked
        // TODO add your handling code here:
        baraja.reiniciarBaraja(); 


        String[] cartaJugador = baraja.robarCarta();
        String[] cartaMaquina = baraja.robarCarta();


        ImageIcon imgJugador = new ImageIcon(getClass().getResource(cartaJugador[1]));
        ImageIcon imgMaquina = new ImageIcon(getClass().getResource(cartaMaquina[1]));

        cartaJ.setIcon(imgJugador);
        
        
        cartaM.setIcon(imgMaquina);

        int valorJugador = obtenerValorCarta(cartaJugador[0]);
        int valorMaquina = obtenerValorCarta(cartaMaquina[0]);

        String mensaje;
        if (valorJugador > valorMaquina) {
            mensaje = "¡Has ganado!";
            ganarapuesta();
        } else if (valorJugador < valorMaquina) {
            mensaje = "La máquina ha ganado.";
            perdidaapuesta();
        } else {
            mensaje = "Es un empate.";
        }

        JOptionPane.showMessageDialog(null, mensaje, "Resultado", JOptionPane.INFORMATION_MESSAGE);
        cartaJ.setIcon(imagen);
        cartaM.setIcon(imagen);
        comprobaciondinero=dinerouser;
        apuestaenvivo=0;
        apuest.setIcon(null);
    }//GEN-LAST:event_cartaJMouseClicked
    private int obtenerValorCarta(String nombreCarta) {
        String valor = nombreCarta.split("_")[1];
        switch (valor) {
            case "J":
                return 10;
            case "Q": 
                return 11;
            case "K":
                return 12;
            case "1":
                return 1;
            default:
                return Integer.parseInt(valor);
        }
    }
    private void apostando() {
    int nuevaApuesta = 0;

    switch (apostador) {
        case cinco:
            nuevaApuesta = 5;
            break;
        case diez:
            nuevaApuesta = 10;
            break;
        case veinticinco:
            nuevaApuesta = 25;
            break;
        case cincuenta:
            nuevaApuesta = 50;
            break;
        case setentaycinco:
            nuevaApuesta = 75;
            break;
        case cien:
            nuevaApuesta = 100;
            break;
    }

    if (apuestaenvivo + nuevaApuesta > comprobaciondinero) {
        JOptionPane.showMessageDialog(this, "No tienes suficientes fondos para esta apuesta.");
        return;
    }
    apuestaenvivo += nuevaApuesta;
    apuest.setIcon(imagen2);
}

    private void perdidaapuesta() {
    dinerouser = dinerouser - apuestaenvivo;
    userdao.actualizarDinero(usuar, dinerouser);
}

    private void ganarapuesta() {
    dinerouser = dinerouser + apuestaenvivo;
    userdao.actualizarDinero(usuar, dinerouser);

}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(CA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(CA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(CA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(CA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new CA().setVisible(true);
        }
    });
}
    class FondoPanel extends JPanel {

    private Image imagen;

    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon(getClass().getResource("/CA/fondoca.jpg")).getImage();

        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

        setOpaque(false);

        super.paint(g);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apuest;
    private javax.swing.JLabel cartaJ;
    private javax.swing.JLabel cartaM;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel cien;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel cincuenta;
    private javax.swing.JLabel diez;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jug;
    private javax.swing.JLabel money;
    private javax.swing.JLabel retroceder;
    private javax.swing.JLabel setentaycinco;
    private javax.swing.JLabel sis;
    private javax.swing.JLabel veinticinco;
    // End of variables declaration//GEN-END:variables
}
