package PPT;

import Menu.Menu;
import Menu.UsuarioDAO;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aazur
 */
public class ppt extends javax.swing.JFrame {

    FondoPanel panel = new FondoPanel();
    int contJ = 0;
    int contM = 0;
    String nombreusuario;

    enum Resultado {
        Piedra,
        Papel,
        Tijera,
        Ninguna
    }
    Resultado operacion = Resultado.Ninguna;
    Random rd = new Random(3);
    int dinerouser = 0;

    enum Apostar {
        cinco,
        diez,
        veinticinco,
        cincuenta,
        setentaycinco,
        cien,
        cero

    }
    private static int comprobaciondinero = 0;
    Apostar apostador = Apostar.cero;
    private static int apuestaenvivo = 0;
    ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Dados/fichicas.png"));
    private static UsuarioDAO userdao = new UsuarioDAO();

    /**
     * Creates new form Parejas
     *
     * @param usuario
     * @param dinero
     */
    public ppt(String usuario, int dinero) {

        this.setContentPane(panel);
        initComponents();
        if (usuario != null) {
            player.setText(usuario);
        }
        dinerouser = dinero;
        comprobaciondinero=dinero;
        nombreusuario = usuario;
    }

    public ppt() {
        this.setContentPane(panel);
        initComponents();
    }

    private void jugar(Resultado eleccionJugador) {
        Resultado[] posibilidades = Resultado.values();
        Resultado maquina = posibilidades[rd.nextInt(3)];

        // Cargar imágenes
        ImageIcon iconop = new ImageIcon(getClass().getResource("/PPT/piedra.png"));
        ImageIcon iconopap = new ImageIcon(getClass().getResource("/PPT/papel.png"));
        ImageIcon iconotij = new ImageIcon(getClass().getResource("/PPT/tijeras.png"));

        // Asignar imagen según la elección de la máquina
        switch (maquina) {
            case Piedra:
                eleccionmaquina.setIcon(iconop);
                break;
            case Papel:
                eleccionmaquina.setIcon(iconopap);
                break;
            case Tijera:
                eleccionmaquina.setIcon(iconotij);
                break;
        }

        // Determinar el resultado
        if (eleccionJugador == maquina) {
            resultado.setText("Empate");
            reseteo();
        } else if ((eleccionJugador == Resultado.Piedra && maquina == Resultado.Tijera)
                || (eleccionJugador == Resultado.Papel && maquina == Resultado.Piedra)
                || (eleccionJugador == Resultado.Tijera && maquina == Resultado.Papel)) {
            resultado.setText("Gana Jugador");
            ganarapuesta();
            reseteo();
            contJ++;
        } else {
            resultado.setText("Gana Máquina");
            perdidaapuesta();
            reseteo();
            contM++;
        }

        // Actualizar marcador
        victoriasjugador.setText("Victorias Jugador: " + contJ);
        victoriasmaquina.setText("Victorias Máquina: " + contM);
    }

    private void reseteo() {
        apuestaenvivo = 0;
        apuest.setIcon(null);
        comprobaciondinero = dinerouser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugar = new javax.swing.JButton();
        papel = new javax.swing.JLabel();
        piedra = new javax.swing.JLabel();
        tijera = new javax.swing.JLabel();
        eleccionmaquina = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        player = new javax.swing.JLabel();
        maquina = new javax.swing.JLabel();
        victoriasjugador = new javax.swing.JLabel();
        victoriasmaquina = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        retroceder = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        diez = new javax.swing.JLabel();
        apuest = new javax.swing.JLabel();
        veinticinco = new javax.swing.JLabel();
        setentaycinco = new javax.swing.JLabel();
        cien = new javax.swing.JLabel();
        cincuenta = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        money = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        jugar.setBackground(new java.awt.Color(153, 0, 153));
        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PPT/papel.png"))); // NOI18N
        papel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                papelMouseClicked(evt);
            }
        });

        piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PPT/piedra.png"))); // NOI18N
        piedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piedraMouseClicked(evt);
            }
        });

        tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PPT/tijeras.png"))); // NOI18N
        tijera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tijeraMouseClicked(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(153, 0, 153));
        titulo.setText("PIEDRA-PAPEL-TIJERA");

        player.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        player.setForeground(new java.awt.Color(153, 0, 153));
        player.setText("Jugador");

        maquina.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        maquina.setForeground(new java.awt.Color(153, 0, 153));
        maquina.setText("Rival");

        victoriasjugador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        victoriasjugador.setForeground(new java.awt.Color(153, 0, 153));
        victoriasjugador.setText("Victorias:");

        victoriasmaquina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        victoriasmaquina.setForeground(new java.awt.Color(153, 0, 153));
        victoriasmaquina.setText("Victorias:");

        resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(153, 0, 153));
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultado.setText("Resultado:");

        retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/return.png"))); // NOI18N
        retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retrocederMouseClicked(evt);
            }
        });

        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza5.png"))); // NOI18N
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });

        diez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza10.png"))); // NOI18N
        diez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diezMouseClicked(evt);
            }
        });

        apuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apuestMouseClicked(evt);
            }
        });

        veinticinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza25.png"))); // NOI18N
        veinticinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veinticincoMouseClicked(evt);
            }
        });

        setentaycinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/moneda75 (2).png"))); // NOI18N
        setentaycinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setentaycincoMouseClicked(evt);
            }
        });

        cien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza100.png"))); // NOI18N
        cien.setToolTipText("");
        cien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cienMouseClicked(evt);
            }
        });

        cincuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza50.png"))); // NOI18N
        cincuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincuentaMouseClicked(evt);
            }
        });

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/close.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        money.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/mony2.png"))); // NOI18N
        money.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(retroceder)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(titulo)
                                        .addGap(192, 192, 192)))
                                .addComponent(money)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cerrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(papel)
                                            .addComponent(victoriasjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(piedra)
                                            .addComponent(tijera))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(184, 184, 184)
                                        .addComponent(jugar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                                        .addComponent(apuest, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(245, 245, 245)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(victoriasmaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maquina)
                                    .addComponent(eleccionmaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diez)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veinticinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setentaycinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cien)))
                        .addGap(315, 315, 315))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(retroceder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cerrar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(money)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(victoriasmaquina)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maquina)
                        .addGap(150, 150, 150)
                        .addComponent(eleccionmaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(papel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(piedra)
                                .addGap(54, 54, 54)
                                .addComponent(tijera)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(victoriasjugador)
                                    .addComponent(jugar)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apuest, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)))))
                .addGap(18, 18, 18)
                .addComponent(resultado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cinco)
                    .addComponent(diez)
                    .addComponent(veinticinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setentaycinco)
                    .addComponent(cincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cien))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tijeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tijeraMouseClicked
        // TODO add your handling code here:
        operacion = Resultado.Tijera;
    }//GEN-LAST:event_tijeraMouseClicked

    private void piedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piedraMouseClicked
        // TODO add your handling code here:
        operacion = Resultado.Piedra;
    }//GEN-LAST:event_piedraMouseClicked

    private void papelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseClicked
        // TODO add your handling code here:
        operacion = Resultado.Papel;
    }//GEN-LAST:event_papelMouseClicked

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
        if (operacion != Resultado.Ninguna) {
            jugar(operacion);
        } else {
            resultado.setText("Selecciona una opción antes de jugar");
        }

    }//GEN-LAST:event_jugarActionPerformed

    private void retrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrocederMouseClicked
        // TODO add your handling code here:

        this.setVisible(false); // Oculta la ventana actual
        new Menu().setVisible(true); // Crea y muestra el menú principal con el dinero actual
        this.dispose(); // Libera los recursos de la ventana actual


    }//GEN-LAST:event_retrocederMouseClicked

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cinco;
        apostando();
    }//GEN-LAST:event_cincoMouseClicked

    private void diezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diezMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.diez;
        apostando();
    }//GEN-LAST:event_diezMouseClicked

    private void apuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apuestMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Estas apostando " + apuestaenvivo);
    }//GEN-LAST:event_apuestMouseClicked

    private void veinticincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veinticincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.veinticinco;
        apostando();
    }//GEN-LAST:event_veinticincoMouseClicked

    private void setentaycincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setentaycincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.setentaycinco;
        apostando();
    }//GEN-LAST:event_setentaycincoMouseClicked

    private void cienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cienMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cien;
        apostando();
    }//GEN-LAST:event_cienMouseClicked

    private void cincuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincuentaMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cincuenta;
        apostando();
    }//GEN-LAST:event_cincuentaMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO?", "SALIR", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_cerrarMouseClicked

    private void moneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Tu saldo es de $"+dinerouser);
    }//GEN-LAST:event_moneyMouseClicked

    private void apostando() {
        int nuevaApuesta = 0;

        switch (apostador) {
            case cinco:
                nuevaApuesta = 5;
                break;
            case diez:
                nuevaApuesta = 10;
                break;
            case veinticinco:
                nuevaApuesta = 25;
                break;
            case cincuenta:
                nuevaApuesta = 50;
                break;
            case setentaycinco:
                nuevaApuesta = 75;
                break;
            case cien:
                nuevaApuesta = 100;
                break;
        }

        if (apuestaenvivo + nuevaApuesta > comprobaciondinero) {
            JOptionPane.showMessageDialog(this, "No tienes suficientes fondos para esta apuesta.");
            return;
        }
        apuestaenvivo += nuevaApuesta;
        apuest.setIcon(imagen2);
    }

    private void perdidaapuesta() {
        dinerouser = dinerouser - apuestaenvivo;
        userdao.actualizarDinero(nombreusuario, dinerouser);
    }

    private void ganarapuesta() {
        dinerouser = dinerouser + apuestaenvivo;
        userdao.actualizarDinero(nombreusuario, dinerouser);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ppt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ppt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ppt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ppt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ppt().setVisible(true);
            }
        });
    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/PPT/fondoPPT.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apuest;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel cien;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel cincuenta;
    private javax.swing.JLabel diez;
    private javax.swing.JLabel eleccionmaquina;
    private javax.swing.JButton jugar;
    private javax.swing.JLabel maquina;
    private javax.swing.JLabel money;
    private javax.swing.JLabel papel;
    private javax.swing.JLabel piedra;
    private javax.swing.JLabel player;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel retroceder;
    private javax.swing.JLabel setentaycinco;
    private javax.swing.JLabel tijera;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel veinticinco;
    private javax.swing.JLabel victoriasjugador;
    private javax.swing.JLabel victoriasmaquina;
    // End of variables declaration//GEN-END:variables
}
