/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dados;

import Menu.Menu;
import Menu.UsuarioDAO;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aazur
 */
public class Dados extends javax.swing.JFrame {

    enum Apostar {
        cinco,
        diez,
        veinticinco,
        cincuenta,
        setentaycinco,
        cien,
        cero

    }
    private static int comprobaciondinero = 0;
    Apostar apostador = Apostar.cero;
    private static int apuestaenvivo = 0;
    ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Dados/fichicas.png"));
    ImageIcon imagen = new ImageIcon(getClass().getResource("/Dados/dado.png"));
    private static UsuarioDAO userdao = new UsuarioDAO();
    private static String usuar;

    FondoPanel panel = new FondoPanel();
    Random rd = new Random();
    int sumajugador = 0;
    int sumamaquina = 0;
    private ImageIcon[] dados;

    int dinerouser = 0;

    /**
     * Creates new form Dados
     *
     * @param usuario
     * @param dinero
     */
    public Dados(String usuario, int dinero) {
        this.setContentPane(panel);
        this.setContentPane(panel);
        this.dados = new ImageIcon[]{
            new ImageIcon(getClass().getResource("/Dados/dado1.png")),
            new ImageIcon(getClass().getResource("/Dados/dado2.png")),
            new ImageIcon(getClass().getResource("/Dados/dado3.png")),
            new ImageIcon(getClass().getResource("/Dados/dado4.png")),
            new ImageIcon(getClass().getResource("/Dados/dado5.png")),
            new ImageIcon(getClass().getResource("/Dados/dado6.png"))
        };
        dinerouser = dinero;
        comprobaciondinero = dinerouser;
        initComponents();
        if (usuario != null) {
            lanzamiento1.setText("Lanzamiento " + usuario);
        }
        usuar = usuario;
    }

    public Dados() {
        this.setContentPane(panel);
        this.dados = new ImageIcon[]{
            new ImageIcon(getClass().getResource("/Dados/dado1.png")),
            new ImageIcon(getClass().getResource("/Dados/dado2.png")),
            new ImageIcon(getClass().getResource("/Dados/dado3.png")),
            new ImageIcon(getClass().getResource("/Dados/dado4.png")),
            new ImageIcon(getClass().getResource("/Dados/dado5.png")),
            new ImageIcon(getClass().getResource("/Dados/dado6.png"))
        };

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        dosdados = new javax.swing.JLabel();
        lanzamiento1 = new javax.swing.JLabel();
        lanzamiento2 = new javax.swing.JLabel();
        jugadordado = new javax.swing.JLabel();
        maquinadado = new javax.swing.JLabel();
        suma1 = new javax.swing.JLabel();
        suma2 = new javax.swing.JLabel();
        retroceder = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        diez = new javax.swing.JLabel();
        veinticinco = new javax.swing.JLabel();
        setentaycinco = new javax.swing.JLabel();
        cien = new javax.swing.JLabel();
        cincuenta = new javax.swing.JLabel();
        apuest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 204, 204));
        titulo.setText("LA SUERTE DE LOS DADOS");

        dosdados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/ambosdados.png"))); // NOI18N

        lanzamiento1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lanzamiento1.setForeground(new java.awt.Color(0, 204, 204));
        lanzamiento1.setText("Lanzamiento jugador");

        lanzamiento2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lanzamiento2.setForeground(new java.awt.Color(0, 204, 204));
        lanzamiento2.setText("Lanzamiento rival");

        jugadordado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugadordado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/dado.png"))); // NOI18N
        jugadordado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugadordadoMouseClicked(evt);
            }
        });

        maquinadado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maquinadado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/dado.png"))); // NOI18N

        suma1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        suma1.setForeground(new java.awt.Color(0, 204, 204));
        suma1.setText("Suma total:");

        suma2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        suma2.setForeground(new java.awt.Color(0, 204, 204));
        suma2.setText("Suma total:");

        retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/return.png"))); // NOI18N
        retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retrocederMouseClicked(evt);
            }
        });

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/close.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        money.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/mony2.png"))); // NOI18N
        money.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyMouseClicked(evt);
            }
        });

        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza5.png"))); // NOI18N
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });

        diez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza10.png"))); // NOI18N
        diez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diezMouseClicked(evt);
            }
        });

        veinticinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza25.png"))); // NOI18N
        veinticinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veinticincoMouseClicked(evt);
            }
        });

        setentaycinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/moneda75 (2).png"))); // NOI18N
        setentaycinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setentaycincoMouseClicked(evt);
            }
        });

        cien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza100.png"))); // NOI18N
        cien.setToolTipText("");
        cien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cienMouseClicked(evt);
            }
        });

        cincuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/monedas/monedaza50.png"))); // NOI18N
        cincuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincuentaMouseClicked(evt);
            }
        });

        apuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apuestMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(retroceder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lanzamiento2)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(money)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cerrar)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dosdados)
                        .addGap(75, 75, 75)
                        .addComponent(maquinadado, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lanzamiento1)
                            .addComponent(suma1)
                            .addComponent(jugadordado, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diez)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veinticinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setentaycinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cien))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(apuest, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(suma2)))
                        .addContainerGap(167, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lanzamiento1)
                        .addGap(18, 18, 18)
                        .addComponent(jugadordado, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suma1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
                                .addComponent(apuest, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cerrar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(money))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(retroceder)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(titulo)))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dosdados)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lanzamiento2)
                                                .addGap(18, 18, 18)
                                                .addComponent(maquinadado, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suma2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cinco)
                    .addComponent(diez)
                    .addComponent(veinticinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setentaycinco)
                    .addComponent(cincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cien))
                .addGap(85, 85, 85))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jugadordadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugadordadoMouseClicked
        // TODO add your handling code here:
        jugar();
    }//GEN-LAST:event_jugadordadoMouseClicked

    private void retrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrocederMouseClicked
        // TODO add your handling code here:
        this.setVisible(false); // Oculta la ventana actual
        new Menu().setVisible(true); // Crea y muestra el menú principal con el dinero actual
        this.dispose(); // Libera los recursos de la ventana actual


    }//GEN-LAST:event_retrocederMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO?", "SALIR", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_cerrarMouseClicked

    private void moneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Tu saldo es de $" + dinerouser);
    }//GEN-LAST:event_moneyMouseClicked

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cinco;
        apostando();
    }//GEN-LAST:event_cincoMouseClicked

    private void diezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diezMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.diez;
        apostando();
    }//GEN-LAST:event_diezMouseClicked

    private void veinticincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veinticincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.veinticinco;
        apostando();
    }//GEN-LAST:event_veinticincoMouseClicked

    private void setentaycincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setentaycincoMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.setentaycinco;
        apostando();
    }//GEN-LAST:event_setentaycincoMouseClicked

    private void cienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cienMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cien;
        apostando();
    }//GEN-LAST:event_cienMouseClicked

    private void cincuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincuentaMouseClicked
        // TODO add your handling code here:
        apostador = Apostar.cincuenta;
        apostando();
    }//GEN-LAST:event_cincuentaMouseClicked

    private void apuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apuestMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Estas apostando " + apuestaenvivo);
    }//GEN-LAST:event_apuestMouseClicked
    private void apostando() {
        int nuevaApuesta = 0;

        switch (apostador) {
            case cinco:
                nuevaApuesta = 5;
                break;
            case diez:
                nuevaApuesta = 10;
                break;
            case veinticinco:
                nuevaApuesta = 25;
                break;
            case cincuenta:
                nuevaApuesta = 50;
                break;
            case setentaycinco:
                nuevaApuesta = 75;
                break;
            case cien:
                nuevaApuesta = 100;
                break;
        }

        if (apuestaenvivo + nuevaApuesta > comprobaciondinero) {
            JOptionPane.showMessageDialog(this, "No tienes suficientes fondos para esta apuesta.");
            return;
        }
        apuestaenvivo += nuevaApuesta;
        apuest.setIcon(imagen2);
    }

    private void perdidaapuesta() {
        dinerouser = dinerouser - apuestaenvivo;
        userdao.actualizarDinero(usuar, dinerouser);
    }

    private void ganarapuesta() {
        dinerouser = dinerouser + apuestaenvivo;
        userdao.actualizarDinero(usuar, dinerouser);

    }

    public void jugar() {
        int dadoJugador = rd.nextInt(6) + 1;
        int dadoMaquina = rd.nextInt(6) + 1;

        sumajugador = sumajugador + dadoJugador;
        sumamaquina = sumamaquina + dadoMaquina;

        suma1.setText("Suma total: " + sumajugador);
        suma2.setText("Suma total: " + sumamaquina);

        actualizarDado(jugadordado, dadoJugador);
        actualizarDado(maquinadado, dadoMaquina);
        if (sumajugador > 20 && sumamaquina < sumajugador) {
            JOptionPane.showMessageDialog(this, "Ha ganado el jugador!");
            ganarapuesta();
            apuestaenvivo = 0;
            apuest.setIcon(null);
            comprobaciondinero = dinerouser;
            acabar();
        }
        if (sumamaquina > 20 && sumamaquina > sumajugador) {
            JOptionPane.showMessageDialog(this, "Ganó la máquina!");
            perdidaapuesta();
            apuestaenvivo = 0;
            apuest.setIcon(null);
            comprobaciondinero = dinerouser;
            acabar();
        }
    }

    private void actualizarDado(JLabel label, int dado) {
        label.setIcon(dados[dado - 1]); // Se usa el array directamente

    }

    private void acabar() {

        suma1.setText("Suma total: ");
        suma2.setText("Suma total: ");
        jugadordado.setIcon(imagen);
        maquinadado.setIcon(imagen);
        sumajugador = 0;
        sumamaquina = 0;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/Dados/fondodado.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apuest;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel cien;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel cincuenta;
    private javax.swing.JLabel diez;
    private javax.swing.JLabel dosdados;
    private javax.swing.JLabel jugadordado;
    private javax.swing.JLabel lanzamiento1;
    private javax.swing.JLabel lanzamiento2;
    private javax.swing.JLabel maquinadado;
    private javax.swing.JLabel money;
    private javax.swing.JLabel retroceder;
    private javax.swing.JLabel setentaycinco;
    private javax.swing.JLabel suma1;
    private javax.swing.JLabel suma2;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel veinticinco;
    // End of variables declaration//GEN-END:variables
}
