/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

import Menu.Menu;
import Menu.Usuario;
import Menu.UsuarioDAO;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author aazur
 */
public class Pantalla extends javax.swing.JFrame {
    FondoPanel panel = new FondoPanel();
    private static UsuarioDAO usuarioDAO = new UsuarioDAO();
    private static String player;
    private static int dinerousuario = 0;
    
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        this.setContentPane(panel);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciar = new javax.swing.JLabel();
        crearuser = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        iniciar.setBackground(new java.awt.Color(0, 0, 0));
        iniciar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
        });

        crearuser.setBackground(new java.awt.Color(0, 0, 0));
        crearuser.setToolTipText("");
        crearuser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        crearuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearuserMouseClicked(evt);
            }
        });

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/close.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearuser, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearuser, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void crearuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearuserMouseClicked
        // TODO add your handling code here:
                String usuario = JOptionPane.showInputDialog(null, "Elige un nombre de usuario:", "Crear usuario", JOptionPane.QUESTION_MESSAGE);
        if (usuario == null || usuario.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            return;
        }

        String contraseña = JOptionPane.showInputDialog(null, "Elige una contraseña:", "Crear usuario", JOptionPane.QUESTION_MESSAGE);
        if (contraseña == null || contraseña.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La contraseña no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            return;
        }

        String dineroStr = JOptionPane.showInputDialog(null, "Introduce la cantidad de dinero inicial:", "Crear usuario", JOptionPane.QUESTION_MESSAGE);
        if (dineroStr == null || dineroStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un valor numérico para el dinero inicial.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            return;
        }

        try {
            int dinero = Integer.parseInt(dineroStr);
            if (dinero < 0) {
                JOptionPane.showMessageDialog(null, "El dinero inicial no puede ser negativo.", "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
                return;
            }

            Usuario newUser = new Usuario(usuario, contraseña, dinero);
            boolean creado = usuarioDAO.crearUsuario(newUser); // Verifica si el usuario se creó correctamente

            if (creado) {
                dinerousuario = dinero;
                player = usuario;
                JOptionPane.showMessageDialog(null, "Usuario creado con éxito. Bienvenido, " + usuario + "!", "Usuario creado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "El usuario ya existe. Intenta con otro nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un número válido para el dinero.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        Menu menu= new Menu(player,dinerousuario);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearuserMouseClicked

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        // TODO add your handling code here:
        String usuario = JOptionPane.showInputDialog(null, "Introduce tu usuario:", "Inicio de sesión", JOptionPane.QUESTION_MESSAGE);
        if (usuario == null) {
            System.exit(0);
            return;
        }
        player = usuario;
        String contraseña = JOptionPane.showInputDialog(null, "Introduce tu contraseña:", "Inicio de sesión", JOptionPane.QUESTION_MESSAGE);
        if (contraseña == null) {
            System.exit(0);
            return;
        }

        Usuario user = usuarioDAO.iniciarSesion(usuario, contraseña);
        if (user != null) {
            dinerousuario = user.getDinero();

            JOptionPane.showMessageDialog(null, "Bienvenido, " + usuario + "! \nDinero disponible: $" + dinerousuario, "Sesión iniciada", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        Menu menu= new Menu(player,dinerousuario);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_iniciarMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO?", "SALIR", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_cerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);               

            }
        });
    }
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Pantalla/pantallita.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel crearuser;
    private javax.swing.JLabel iniciar;
    // End of variables declaration//GEN-END:variables
}
